[project]
name = 'banking-regulatory-technology-contract'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.automated-regulatory-reporting-and-compliance]
path = 'contracts/automated-regulatory-reporting-and-compliance.clar'
clarity_version = 2
epoch = 2.5

[contracts.real-time-risk-monitoring-and-alert-systems]
path = 'contracts/real-time-risk-monitoring-and-alert-systems.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
